### ISSUE TITLE
Add Sniff to check for the use of instance of function

### ISSUE THREAD

**Issue by Exadra37** [bmitch/Codor#102]
A sniff to disallow the use of instanceof function would be good to have.

The use of it is a code smell and represents a flaw in the project Software Architecture.

I love this package that helps us to write more SOLID and Clean Code.

**Comment by bmitch** [comment]
@Exadra37 Thank you for the great suggestion.

It is possible to sniff for using a default sniff included with PHP Code Sniffer. It is the `Generic.PHP.ForbiddenFunctions` sniff.

To apply, you can add this to your xml file used by PHP Code Sniffer:

```xml
<rule ref="Generic.PHP.ForbiddenFunctions">
  <properties>
    <property name="forbiddenFunctions" type="array" value="instanceof=>null"/>
  </properties>
</rule>
```
In that case I will leave this out of Codor since it is included within the default sniffs provided by PHPCS.
