### ISSUE TITLE
What issue choice for contribution?

### ISSUE THREAD

**Issue by kevin-schmitt** [bmitch/Codor#151]
Hello,

I want to do a PR but,
All issues is again valid? What is roadmap for next features or bugs? 
Can you assign to me is maybe more simple please.

Thanks

**Comment by bmitch** [comment]
Hi @kevin-schmitt thanks for your interest.

No roadmap really. Some of the issues are quite old so may no longer be valid so you may want to comment on them before you write any code because of that.

@villfa has done the majority of the maintaining of this project lately so they may have some ideas that you could work on.

Otherwise feel free to submit a PR. Thanks!

**Comment by villfa** [comment]
Hi @kevin-schmitt,

It's great that you want to contribute.

Take a look at the bug report #130. I think it shouldn't be too hard to fix.
Please tell me if you need some guidance (and we can switch to french if it's easier for you ;) ).

**Comment by kevin-schmitt** [comment]
Thanks for you comeback :)

I go to that then.
